name: Docker Image CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build and test:

    runs-on: ubuntu-latest


    steps:
    - name: Checkout Branch
      uses: actions/checkout@v4

    # -----------------------------------------------------
    # Setup Environment for Checks
    # -----------------------------------------------------
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'
    
    - name: Set up dependencies
      run: pip install -r requirements.txt

    # -----------------------------------------------------
    # Linting
    # -----------------------------------------------------

    - name: Run Black formatter check
      run: black --check .

    - name: Run flake8 tests
      run: flake8 .

    - name: Run Bandit (SAST)
      run: bandit -r . -ll -x tests/

    - name: Run dependency check
      run: safety check -r requirements.txt

    # -----------------------------------------------------
    # Create Docker Image (Runs on all Branches)
    # -----------------------------------------------------
    - name: Setup Docker Builder
      uses: docker/setup-buildx-action@v3

    - name: Build the Docker image
      uses: docker/build-push-action@v6
      with:
        push: false
        tags: ${{ env.IMAGE_NAME }}:${{ github.head_ref || github.ref_name }}
        cache-from: type=gha
        cache-to: type=gha,mode=max



      